import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray10001,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.gray30003,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(9.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primaryContainer,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blueGray10001,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodySmall: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 9.fSize,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 12.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 10.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 9.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onErrorContainer,
          fontSize: 20.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w900,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray90001,
          fontSize: 14.fSize,
          fontFamily: 'Lato',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF00539B),
    primaryContainer: Color(0XFFE8F3FA),
    secondary: Color(0XFFE8F3FA),
    secondaryContainer: Color(0X2800539B),
    tertiary: Color(0XFFE8F3FA),
    tertiaryContainer: Color(0X2800539B),

    // Background colors
    background: Color(0XFFE8F3FA),

    // Surface colors
    surface: Color(0XFFE8F3FA),
    surfaceTint: Color(0XFFFFFFFF),
    surfaceVariant: Color(0X2800539B),

    // Error colors
    error: Color(0XFFFFFFFF),
    errorContainer: Color(0XFF495057),
    onError: Color(0XFF2E2E2E),
    onErrorContainer: Color(0XFF121212),

    // On colors(text colors)
    onBackground: Color(0XFF112883),
    onInverseSurface: Color(0XFF2E2E2E),
    onPrimary: Color(0XFFFFFFFF),
    onPrimaryContainer: Color(0XFF112883),
    onSecondary: Color(0XFF112883),
    onSecondaryContainer: Color(0XFFFFFFFF),
    onTertiary: Color(0XFF112883),
    onTertiaryContainer: Color(0XFFFFFFFF),

    // Other colors
    outline: Color(0XFFFFFFFF),
    outlineVariant: Color(0XFFE8F3FA),
    scrim: Color(0XFFE8F3FA),
    shadow: Color(0XFFFFFFFF),

    // Inverse colors
    inversePrimary: Color(0XFFE8F3FA),
    inverseSurface: Color(0XFFFFFFFF),

    // Pending colors
    onSurface: Color(0XFF112883),
    onSurfaceVariant: Color(0XFFFFFFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amberA700 => Color(0XFFF0AD02);

  // Black
  Color get black90004 => Color(0X04000000);

  // Blue
  Color get blue700 => Color(0XFF0575E6);

  // BlueGray
  Color get blueGray100 => Color(0XFFD3D3D3);
  Color get blueGray10001 => Color(0XFFD9D9D9);
  Color get blueGray10002 => Color(0XFFCED4DA);
  Color get blueGray10003 => Color(0XFFD1D1D1);
  Color get blueGray300 => Color(0XFF8A96A4);
  Color get blueGray50 => Color(0XFFEFF2F4);
  Color get blueGray500 => Color(0XFF74788D);
  Color get blueGray50001 => Color(0XFF4C8F9E);
  Color get blueGray700 => Color(0XFF50525F);
  Color get blueGray900 => Color(0XFF333333);

  // Gray
  Color get gray100 => Color(0XFFF0F7FC);
  Color get gray10001 => Color(0XFFF7F7F7);
  Color get gray10002 => Color(0XFFEFF3FD);
  Color get gray10003 => Color(0XFFF5F5F5);
  Color get gray300 => Color(0XFFDFDFDF);
  Color get gray30001 => Color(0XFFE0E0E0);
  Color get gray30002 => Color(0XFFDDE1E6);
  Color get gray30003 => Color(0XFFDBDBDB);
  Color get gray30004 => Color(0XFFE3E3E3);
  Color get gray30005 => Color(0XFFDADADA);
  Color get gray400 => Color(0XFFC4C4C4);
  Color get gray40001 => Color(0XFFB6B6B6);
  Color get gray40002 => Color(0XFFBFBFBF);
  Color get gray40003 => Color(0XFFC9C9C9);
  Color get gray50 => Color(0XFFF8F8FB);
  Color get gray500 => Color(0XFF949494);
  Color get gray50028 => Color(0X28A4A4A4);
  Color get gray70066 => Color(0X66565656);
  Color get gray800 => Color(0XFF393939);
  Color get gray80001 => Color(0XFF44464D);
  Color get gray900 => Color(0XFF191D23);
  Color get gray90001 => Color(0XFF1C1C1C);

  // Grayf
  Color get gray8003f => Color(0X3F383838);

  // Green
  Color get green200 => Color(0XFFACECB3);
  Color get green40030 => Color(0X305AD85F);
  Color get green800 => Color(0XFF278531);

  // Indigo
  Color get indigo900 => Color(0XFF022889);
  Color get indigo90001 => Color(0XFF021B79);

  // LightGreen
  Color get lightGreen800 => Color(0XFF409A08);
  Color get lightGreenA700 => Color(0XFF56BC18);

  // Red
  Color get red300 => Color(0XFFF46A6A);
  Color get red500 => Color(0XFFFA3434);

  // Teal
  Color get teal50 => Color(0XFFD6E1F4);

  // Yellow
  Color get yellowA700 => Color(0XFFFFD600);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
